/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// progdefs.h

/* file generated by qcc, do not modify */

#define PRGLOBALS_BETA
typedef struct
{
#include "prglobals.h"
} globalvars_beta_t;
#undef PRGLOBALS_BETA

typedef struct
{
#include "prglobals.h"
} globalvars_t;


#define PRFIELDS_BETA
typedef struct
{
#include "prfields.h"
} entvars_beta_t;
#undef PRFIELDS_BETA

typedef struct
{
#include "prfields.h"
/*----- end of original struct -----*/
#ifdef HEXEN2_SUPPORT
	float		scale;
	float		drawflags;
	float		abslight;
	float		hull;
	float		stats_restored;
	float		playerclass;
	float		bluemana;
	float		greenmana;
	float		max_mana;
	float		armor_amulet;
	float		armor_bracer;
	float		armor_breastplate;
	float		armor_helmet;
	float		level;
	float		intelligence;
	float		wisdom;
	float		dexterity;
	float		strength;
	float		experience;
	float		ring_flight;
	float		ring_water;
	float		ring_turning;
	float		ring_regeneration;
	float		haste_time;
	float		tome_time;
	string_t	puzzle_inv1;
	string_t	puzzle_inv2;
	string_t	puzzle_inv3;
	string_t	puzzle_inv4;
	string_t	puzzle_inv5;
	string_t	puzzle_inv6;
	string_t	puzzle_inv7;
	string_t	puzzle_inv8;
	float		idealroll;
	float		hoverz;
	float		flags2;
	float		light_level;
	float		friction;
	float		rings_active;
	float		rings_low;
	float		artifact_active;
	float		artifact_low;
	float		hasted;
	float		inventory;
	float		cnt_torch;
	float		cnt_h_boost;
	float		cnt_sh_boost;
	float		cnt_mana_boost;
	float		cnt_teleport;
	float		cnt_tome;
	float		cnt_summon;
	float		cnt_invisibility;
	float		cnt_glyph;
	float		cnt_haste;
	float		cnt_blast;
	float		cnt_polymorph;
	float		cnt_flight;
	float		cnt_cubeofforce;
	float		cnt_invincibility;
	int			cameramode;
	int			movechain;
	func_t		chainmoved;
#endif
} entvars_t;

#define PROGHEADER_CRC         5927		/* 0x00001727 */
#define PROGHEADER_BETA_CRC   26940		/* 0x0000693C - Quake pre-release/beta3 */
